In [2]:
import pandas as pd
from sklearn import datasets
from sklearn.decomposition import PCA

In [3]:
url="https://raw.githubusercontent.com/masterfloss/data/main/dadosMundo.csv" 
df=pd.read_csv(url)

In [4]:
df

,Country,Area_km2,Population,Birth rate(births/1000 population),Death rate(deaths/1000 population),Electricity – consumption(kWh) per capita,Electricity – production(kWh) per capita,GDPpercapita,GDP - real growth rate(%),Industrial production growth rate(%),...,Internet users in the per 1000 people,Investment (gross fixed)(% of GDP),Life expectancy at birth(years),MilitPercentGDP,Oil – consumption(bbl/day) per 1000 persons,Public debt(% of GDP),Telephones - main lines in use per capita,Telephones - mobile cellular per capita,Total fertility rate(children born/woman),Unemploy rate(%)
0,Afghanistan,647500,29928987.0,47.02,20.75,21.791583,18.042709,800.0,7.5,NaN,...,0.033412,NaN,42.90,2.60,0.116943,NaN,0.001106,0.000501,6.75,NaN
1,Akrotiri,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,28748,3563112.0,15.08,5.12,1897.217938,1594.112113,4900.0,5.6,3.1,...,8.419606,18.4,77.24,1.49,2.104902,NaN,0.071567,0.308719,2.04,14.8
3,Algeria,2381740,32531853.0,17.13,4.60,725.750236,791.839309,6600.0,6.1,6.0,...,15.369552,26.2,73.00,3.20,6.424473,37.4,0.067614,0.044489,1.92,25.4
4,American Samoa,199,57881.0,23.13,3.33,2088.768335,2245.987457,8000.0,NaN,NaN,...,NaN,NaN,75.84,NaN,65.651941,NaN,0.259152,0.041067,3.25,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,West Bank,5860,2385615.0,32.37,3.99,NaN,NaN,800.0,6.0,NaN,...,60.780973,NaN,73.08,NaN,NaN,NaN,0.126424,0.201206,4.40,27.2
259,Western Sahara,266000,273008.0,NaN,NaN,306.584422,329.660669,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6.593213,NaN,NaN,NaN,NaN,NaN
260,Yemen,527970,20727063.0,43.07,8.53,136.391731,146.668151,800.0,1.9,3.0,...,4.824610,16.1,61.75,7.80,3.763196,46.4,0.026159,0.019834,6.67,35.0
261,Zambia,752614,11261795.0,41.38,20.23,474.613505,725.195229,900.0,4.6,6.9,...,6.055873,41.4,39.70,1.80,0.976754,127.5,0.007850,0.021400,5.47,50.0
262,Zimbabwe,390580,12746990.0,29.74,24.66,880.207798,693.418603,1900.0,-8.2,-7.8,...,39.224946,9.9,36.67,4.30,1.804348,52.3,0.023606,0.029740,3.54,70.0

In [6]:
df.dtypes

Country                                            object
Area_km2                                            int64
Population                                        float64
Birth rate(births/1000 population)                float64
Death rate(deaths/1000 population)                float64
Electricity – consumption(kWh) per capita         float64
Electricity – production(kWh) per capita          float64
GDPpercapita                                      float64
GDP - real growth rate(%)                         float64
Industrial production growth rate(%)              float64
Infant mortality rate(deaths/1000 live births)    float64
Inflation rate (consumer prices)(%)               float64
Internet users in the per 1000 people             float64
Investment (gross fixed)(% of GDP)                float64
Life expectancy at birth(years)                   float64
MilitPercentGDP                                   float64
Oil – consumption(bbl/day) per 1000 persons       float64
Public debt(% of GDP)                             float64
Telephones - main lines in use per capita         float64
Telephones - mobile cellular per capita           float64
Total fertility rate(children born/woman)         float64
Unemploy rate(%)                                  float64
dtype: object

In [14]:
df['Country']=float('Country')

ValueError: could not convert string to float: 'Country'

In [15]:
X=df.dropna()
PCAModel = PCA(n_components=4)
XPCA = PCAModel.fit(self,X).transform(X)

NameError: name 'self' is not defined